apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-mosquitto
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa-mosquitto
  template:
    metadata:
      labels:
        app: hpa-mosquitto
    spec:
      containers:
      - name: mosquitto
        image: lordchou_mosquitto
        imagePullPolicy: always
        ports:
        - name: mqtt-port
          containerPort: 1883
        resources:
          requests:
            cpu: 500m
