apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring

spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: prometheus
