apiVersion: v1
kind: Service
metadata:
  name: hpa-mosquitto
  namespace: default
  labels:
        app: hpa-mosquitto
spec:
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: 1883
    protocol: TCP
  selector:
    app: hpa-mosquitto
