# Default values for mosquitto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent

mosquitto:
  image: 300421616546.dkr.ecr.us-east-2.amazonaws.com/mosquitto-alpine

prometheus:
  scrape: true

exporter:
  image: 300421616546.dkr.ecr.us-east-2.amazonaws.com/mosquitto-exporter
  port: 9234

service:
  type: LoadBalancer
  port: 1883

replica:
  min: 1
  max: 4

resources:
  requests: 
    cpu: 250m
    memory: 100Mi
  limits:
    cpu: 500m
    memory: 128Mi

resourcesExporter:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi

hpa:
  enabled: true
  cpuPercentage: 80
  memoryAverage: 384Mi
  brokerClientsConnected: 20000